<script>
 debugger
 ejecuta()
 function
  fnExito(resolve, reject) {
  setTimeout(
   () => resolve("Hola"),
   5000)
 }
 function
  fnFalla(resolve, reject) {
  setTimeout(
   () => reject(new Error("ouch")),
   5000)
 }
 async function ejecuta() {
  try {
   const r1 =
    await new Promise(fnExito)
   document.write(
    `Éxito 1 ${r1}<br>`)
  } catch (e) {
   document.write(
    `Falló 1: ${e.message}<br>`)
  }
  try {
   const r2 =
    await new Promise(fnFalla)
   document.write(
    `Éxito 2: ${r2}<br>`)
  } catch (e) {
   document.write(
    `Falló 2: ${e.message}<br>`)
  }
 }
</script>